title: CÃ¢ntece de la Oxigen
markdown: kramdown

cdn:
  css:
    - '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/css/bootstrap.min.css'
    - '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/css/bootstrap-theme.min.css'
  js:
    - '//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js'
    - '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/bootstrap.min.js'
